//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HockeyLeague
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cause_cansel_game
    {
        public int id { get; set; }
        public Nullable<int> GameId { get; set; }
        public string Cause { get; set; }
        public Nullable<System.DateTime> NewDataGame { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
