//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HockeyLeague
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Account_Information
    {
        public int ID { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> GameId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
